# Generated by Django 2.1.7 on 2019-03-15 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('doctor', models.TextField()),
                ('diagnosis', models.TextField()),
                ('recommendation', models.TextField()),
                ('medicine', models.TextField()),
                ('test', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalDetails',
            fields=[
                ('uid', models.IntegerField(db_index=True)),
                ('doctor', models.TextField()),
                ('diagnosis', models.TextField()),
                ('recommendation', models.TextField()),
                ('medicine', models.TextField()),
                ('test', models.TextField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical details',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('gender', models.TextField()),
                ('dob', models.TextField()),
                ('house', models.TextField()),
                ('street', models.TextField()),
                ('landmark', models.TextField()),
                ('postoffice', models.TextField()),
                ('district', models.TextField()),
                ('state', models.TextField()),
                ('pin_code', models.IntegerField()),
            ],
        ),
    ]
