# Generated by Django 2.1.7 on 2019-03-15 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_historicaldetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='uid',
            new_name='aadhar',
        ),
        migrations.RenameField(
            model_name='historicaldetails',
            old_name='uid',
            new_name='aadhar',
        ),
    ]
