# Generated by Django 2.1.7 on 2019-03-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190315_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Details',
        ),
        migrations.RemoveField(
            model_name='historicaldetails',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalDetails',
        ),
    ]
